#!/usr/bin/env python3
"""Builds www/rhymes.js, the offline pronunciation list behind the Rhyme finder and rhyme letters.

Source: the CMU Pronouncing Dictionary (how ~130,000 English words are pronounced), kept to words
that are reasonably common (by the wordfreq word-frequency lists) and sorted most common first.
Each phoneme (with its stress for vowels) is written as one character to keep the file small.

Only ordinary dictionary words are suggested as rhymes (not names like "Dwight" or odd spellings like
"whyte"): a word is suggested if it, or the word it's formed from ("hearts" -> "heart"), is in the
en_US spell-check dictionary in lowercase. Other words are kept (so they can still be looked up and
get rhyme letters) but start with a capital letter in the file, which marks them as not suggested.

Needs:  pip install cmudict wordfreq
        npm pack dictionary-en && tar xzf dictionary-en-*.tgz   (the en_US Hunspell dictionary)
        python3 tools/make-rhymes.py package/index.dic
"""
import json, os, re, sys
import cmudict, wordfreq

MIN_ZIPF = 2.5   # about the 47,000 most common words in the dictionary
VOWELS = "AA AE AH AO AW AY EH ER EY IH IY OW OY UH UW".split()
CONSONANTS = "B CH D DH F G HH JH K L M N NG P R S SH T TH V W Y Z ZH".split()
SYMBOLS = [v + s for v in VOWELS for s in "012"] + CONSONANTS
ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!#$%&()*+,-./:;<=>?@[]^_{}~"
assert len(ALPHABET) >= len(SYMBOLS)
CODE = {p: ALPHABET[i] for i, p in enumerate(SYMBOLS)}

# Hunspell word list: "heart/SM", "Dwight/M", ...
lower, anycase = set(), set()
with open(sys.argv[1], encoding="utf-8") as f:
    next(f)
    for line in f:
        w = line.split("/")[0].strip()
        if not w:
            continue
        anycase.add(w.lower())
        if w[0].islower():
            lower.add(w)
# lyric words the spell-check dictionary leaves out
lower.update("gonna wanna gotta yeah ooh whoa hey ya alright tonight".split())


def base_forms(w):
    """w itself, and the words it may be formed from (hearts -> heart, loved -> love, stopped -> stop)"""
    out = [w]
    def strip(suf, min_stem, extra):
        if not w.endswith(suf) or len(w) - len(suf) < min_stem:
            return
        stem = w[: -len(suf)]
        out.append(stem)
        if extra:
            out.append(stem + "e")                              # loved -> love, nicer -> nice
            if stem[-1] == stem[-2]:
                out.append(stem[:-1])                           # stopped -> stop
        if stem.endswith("i"):
            out.append(stem[:-1] + "y")                         # cried -> cry, happily -> happy
    for suf in ("'s", "s"):
        strip(suf, 3, False)
    strip("es", 3, False)
    for suf in ("ed", "ing", "er", "ers", "est"):
        strip(suf, 3, True)
    strip("d", 3, False)
    for suf in ("ly", "ness", "less", "ful", "ment", "able"):
        strip(suf, 3, False)
    return out


def suggested(w):
    if "'" in w:                                                # I'm, don't, we're
        return w in anycase or w.capitalize() in anycase
    return any(b in lower for b in base_forms(w))


words = []
for word, prons in cmudict.dict().items():
    if not re.fullmatch(r"[a-z]+('[a-z]+)?", word):
        continue
    z = wordfreq.zipf_frequency(word, "en")
    if z < MIN_ZIPF:
        continue
    shown = word if suggested(word) else word.capitalize()
    words.append((-z, shown, "".join(CODE[p] for p in prons[0])))
words.sort()

out = {
    "v": 1,
    "symbols": " ".join(SYMBOLS),
    "alphabet": ALPHABET[:len(SYMBOLS)],
    "words": "|".join(w + " " + p for _, w, p in words),
}
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "www", "rhymes.js")
with open(path, "w") as f:
    f.write("// Generated by tools/make-rhymes.py from the CMU Pronouncing Dictionary (BSD license), filtered with the\n"
            "// SCOWL en_US word list (wordlist.sourceforge.net). Don't edit by hand.\n")
    f.write("window.LYRIC_RHYMES = " + json.dumps(out, separators=(",", ":")) + ";\n")
print(len(words), "words,", sum(1 for _, w, _ in words if w[0].islower()), "suggested,", os.path.getsize(path) // 1024, "KB")
